esphome:
  name: doorbell
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
api:
ota:

switch:
  - platform: restart
    name: Doorbell Restart
  - platform: gpio
    id: relay
    inverted: true
    name: Doorbell Chime
    pin: GPIO0

binary_sensor:
  - platform: gpio
    id: button
    name: Doorbell Button
    pin:
    number: GPIO2
    mode: INPUT_PULLUP
    inverted: true
    filters:
      - delayed_on: 25ms
      - delayed_off: 25ms
    on_press:
      - switch.turn_on: relay
    on_release:
      - switch.turn_off: relay
