esphome:
  name: doorbell
  friendly_name: Doorbell

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Doorbell Fallback Hotspot"
    password: "swablab!"

# Enable logging
logger:
 
# Enable Home Assistant API
api:
 
ota:
  - platform: esphome

button:
  - platform: restart
    name: Restart

switch:
  - platform: gpio
    id: relay
    name: Chime
    pin: GPIO2

binary_sensor:
  - platform: gpio
    id: doorbell_button
    name: Button
    pin: GPIO15
    filters:
      - delayed_on: 50ms
      - delayed_off: 50ms
    on_press: 
      then:
        - switch.turn_on: relay
    on_release:
      then:
        - switch.turn_off: relay
