esphome:
  name: doorbell
  friendly_name: Doorbell

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Doorbell Fallback Hotspot"
    password: "swablab!"

# Enable logging
logger:
 
# Enable Home Assistant API
api:
 
ota:
  - platform: esphome

button:
  - platform: restart
    name: Restart

switch:
  - platform: gpio
    id: relay
    name: Chime
    pin: GPIO2

event:
  - platform: template
    name: Event
    id: doorbell_event
    device_class: doorbell
    event_types:
      - "pressed"
      - "double_pressed"

binary_sensor:
  - platform: gpio
    internal: True
    id: doorbell_button
    name: Button
    pin: GPIO15
    filters:
      - delayed_on: 50ms
      - delayed_off: 50ms
    on_press: 
      then:
        - switch.turn_on: relay
    on_release:
      then:
        - switch.turn_off: relay
    on_click:
      then:
        - event.trigger:
            id: doorbell_event
            event_type: pressed
    on_double_click:
      then:
        - event.trigger:
            id: doorbell_event
            event_type: double_pressed
